"""Alembic environment.

Two things make this file specific to Ideable:

1. `DATABASE_URL` comes from the environment, never from alembic.ini — the same image must run
   against any environment's database (the frontend runtime-config work principle applied to migrations).
2. `configure_mappers()` is called before reading metadata. SQLAlchemy-Continuum generates the
   `*_version`, `transaction` and `transaction_meta` classes lazily; without this, autogenerate
   does not see them and would cheerfully propose dropping the audit trail.
3. `framework_models` is imported alongside `models`. Alembic owns *all* DDL, so every table has
   to be visible in the metadata — a table Alembic cannot see is a table it proposes to drop.
   There is deliberately no `include_object` filter: filtering tables out is how a second owner
   of the schema gets to hide, and one schema owner is the whole point of this design.
"""
import os
import sys
from logging.config import fileConfig

from alembic import context
import sqlalchemy as sa
from sqlalchemy import engine_from_config, pool
from sqlalchemy.orm import configure_mappers

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
# …and THIS directory, so `import framework_ops` resolves. Alembic loads env.py and every migration
# through `load_python_file`, which executes the file WITHOUT putting its directory on sys.path — so
# a module sitting right beside them is not importable by default. env.py runs before any migration,
# so inserting it here fixes both.
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

# Import the models so their tables register on Base.metadata. `app.main` is deliberately NOT
# imported: it builds the FastAPI app and would drag request-time concerns into a migration run.
from app.database import Base  # noqa: E402
from app import models  # noqa: E402,F401
from app import framework_models  # noqa: E402,F401

configure_mappers()

# The audit tables are time-partitioned: `issued_at` is denormalised onto the version
# tables and the primary keys widen to include it. Declared here as well as in the app, or
# autogenerate would propose undoing the conversion on the next migration.
from app.audit_partitioning import apply_audit_partitioning_metadata  # noqa: E402
apply_audit_partitioning_metadata(Base.metadata)

config = context.config
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

database_url = os.getenv("DATABASE_URL")
if not database_url:
    raise RuntimeError("DATABASE_URL is not set — migrations have no database to run against.")
config.set_main_option("sqlalchemy.url", database_url.replace("%", "%%"))

target_metadata = Base.metadata

# ---------------------------------------------------------------------------------------------
# Framework DDL, emitted rather than hand-written
# ---------------------------------------------------------------------------------------------
import framework_ops  # noqa: E402,F401  — registers op.enable_rls() and friends

from alembic.autogenerate import rewriter  # noqa: E402
from alembic.operations import ops as alembic_ops  # noqa: E402

# `tenant_id` -> is this table partitioned by tenant? Read from the models, never listed here: a
# hardcoded list is right the day it is written and silently wrong the first time someone adds an
# entity.
# `m.local_table.name`, NOT `m.class_.__tablename__`: SQLAlchemy-Continuum GENERATES the version
# classes, and a generated class carries `__table__` but no `__tablename__` — so reading the
# attribute raised AttributeError and took the whole migrations job down with it. The mapper knows
# the table for every mapped class, declared or generated.
_TENANT_SCOPED = {
    m.local_table.name: bool(getattr(m.class_, "__tenant_scoped__", False))
    for m in Base.registry.mappers if m.local_table is not None
}
#: Columns a client may substring-filter. Each needs a trigram GIN index or the filter is a
#: sequential scan, and `check_entity_ddl.py` fails the build without one.
_FILTERABLE = {
    m.local_table.name: tuple(getattr(m.class_, "__filterable__", ()) or ())
    for m in Base.registry.mappers if m.local_table is not None
}
_VERSIONED = {
    m.local_table.name for m in Base.registry.mappers
    if m.local_table is not None and getattr(m.class_, "__versioned__", None) is not None
}

writer = rewriter.Rewriter()


@writer.rewrites(alembic_ops.CreateTableOp)
def _expand_new_table(context, revision, op):
    """Expand ONE autogenerated CREATE TABLE into the framework DDL that must accompany it.

    Autogenerate writes the table. The RLS enable+force, the two tenancy policies and the
    hypertable conversion are the steps it does not know about — and that were therefore copied by
    hand into every migration, or forgotten.

    The expansion is written INTO the migration file, visibly, where a human still reviews it. That
    is deliberate: a generator whose output nobody reads is a worse checklist, not a better one.

    Two steps are NOT emitted here, and the omissions are the point:

    - the composite primary key containing the partition column. It must be in `__table_args__` so
      it is rendered inside `op.create_table()` itself — Alembic implements no autogenerate
      detection for free-standing PRIMARY KEY changes, so adding it afterwards produces an EMPTY
      migration rather than an error.
    - the trigram GIN indexes. They are expression-based, and autogenerate cannot round-trip an
      expression index: it emits a drop+create pair on every run even when the database already
      matches. They stay hand-written and `include_object` below keeps them out of the diff.
    """
    table = op.table_name
    base = table[: -len("_version")] if table.endswith("_version") else None
    # A version table's tenancy comes from its BASE table, never from its own entry. Continuum
    # GENERATES the version class and the generated class does not carry `__tenant_scoped__`, so it
    # sits in the map as an explicit False — and `.get(table, <fallback>)` returns that False and
    # never consults the base. The audit twin of a tenant-scoped table then got its hypertable and
    # NO row-level security: one customer's history readable by all of them, in a migration that
    # looks complete. Phase A's checker rejects exactly this, so the generator was writing what the
    # gate forbids.
    if base is not None:
        tenant_scoped = _TENANT_SCOPED.get(base, False)
    else:
        tenant_scoped = _TENANT_SCOPED.get(table, False)

    emitted = [op]
    if tenant_scoped:
        emitted.append(framework_ops.EnableRLSOp(table))
        emitted.append(framework_ops.CreateTenantPoliciesOp(table))
    # The trigram GIN index for every __filterable__ column. `_include_object` keeps these OUT of
    # the diff (autogenerate cannot round-trip an expression index — it would propose DROP+CREATE
    # forever), which is precisely why they have to be emitted here: excluded from the diff and not
    # emitted, they would never be written at all, and the developer would hit Phase A's gate with
    # no generator output to fix it from.
    for column in _FILTERABLE.get(table, ()):
        emitted.append(alembic_ops.CreateIndexOp(
            f"idx_{table}_{column}_trgm", table, [column],
            postgresql_using="gin", postgresql_ops={column: "gin_trgm_ops"},
        ))

    # The hypertable conversion is NOT emitted here: it must run AFTER this table's indexes, and a
    # rewrite rule only sees its own CreateTableOp. `_convert_hypertables_last` below appends it to
    # the end of the migration, which is also the order the hand-written baseline uses.
    return emitted


def _convert_hypertables_last(upgrade_ops):
    """Append `create_hypertable` for every version table this migration creates — at the END.

    Ordering is not cosmetic here. `create_hypertable` creates TimescaleDB's own default index on
    the time column, named `<table>_<time_column>_idx` — which is the SAME name autogenerate emits
    for the `issued_at DESC` index the model declares. Convert first and the migration dies on
    `relation "…_version_issued_at_idx" already exists`; convert last and the index already exists,
    so TimescaleDB adopts it and creates nothing.

    That is exactly the order the hand-written baseline migration used, for the same reason.
    """
    tables = [
        op.table_name for op in upgrade_ops.ops
        if isinstance(op, alembic_ops.CreateTableOp)
        and op.table_name.endswith("_version")
        and op.table_name[: -len("_version")] in _VERSIONED
    ]
    for table in tables:
        upgrade_ops.ops.append(framework_ops.CreateHypertableOp(table))


def _process_revision_directives(context, revision, directives):
    """Rewriter first (per-table DDL), then the ordering-sensitive pass over the whole migration."""
    writer(context, revision, directives)
    for script in directives:
        if getattr(script, "upgrade_ops", None) is not None:
            _convert_hypertables_last(script.upgrade_ops)


def _include_name(name, type_, parent_names):
    """Keep TimescaleDB's internals out of the diff — BEFORE they are reflected.

    `include_name` runs earlier than `include_object`, so the chunk tables are never reflected at
    all. Filtering them later works but pays the reflection cost on every autogenerate, and a
    hypertable's chunks are numerous.
    """
    if type_ == "schema":
        return name not in {
            "_timescaledb_internal", "_timescaledb_catalog", "_timescaledb_config",
            "_timescaledb_cache", "timescaledb_information", "timescaledb_experimental",
        }
    return True


def _include_object(obj, name, type_, reflected, compare_to):
    """Exclude the expression indexes autogenerate cannot round-trip.

    A trigram GIN index is `USING gin (col gin_trgm_ops)` — an expression, not a plain column. The
    diff cannot reproduce it, so it proposes DROP + CREATE on every run against a database that
    already has exactly that index. Excluding them is not hiding a problem: they are asserted by
    `scripts/common/check_entity_ddl.py`, which reads the schema rather than diffing it.
    """
    if type_ != "index":
        return True
    # Structural first: any GIN index using a trigram operator class, whatever it is called. The
    # earlier version matched only names ending `_trgm`, so a module that named its index anything
    # else got the perpetual DROP+CREATE this function exists to prevent — the check looked right
    # because the reference module happens to follow the naming convention.
    ops = {}
    try:
        ops = dict((obj.dialect_options.get("postgresql", {}) or {}).get("ops", {}) or {})
    except Exception:                                    # reflected indexes may carry no options
        ops = {}
    if any("trgm" in str(v) for v in ops.values()):
        return False
    # Any expression index — autogenerate cannot round-trip one. `expressions` is absent on a
    # sparsely-reflected index, which is not an error: it just means there is nothing to inspect.
    expressions = getattr(obj, "expressions", None) or ()
    if any(not isinstance(e, sa.Column) for e in expressions):
        return False
    return not (name and name.endswith("_trgm"))         # fallback when reflection told us nothing


def run_migrations_offline() -> None:
    context.configure(
        url=database_url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        compare_type=True,
        process_revision_directives=_process_revision_directives,
        include_name=_include_name,
        include_object=_include_object,
        # Server defaults are compared too. Without this, autogenerate is BLIND to them: adding
        # `server_default=text("true")` to a model produced an EMPTY migration while the database
        # had no default at all, so `alembic check` reported the schema in sync when it was not.
        # That blindness is how two NOT NULL flags ended up with no database default, and every
        # writer that was not the ORM had to remember to supply them.
        compare_server_default=True,
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            compare_type=True,
            compare_server_default=True,
            process_revision_directives=_process_revision_directives,
            include_name=_include_name,
            include_object=_include_object,
        )
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
