#!/usr/bin/env python3
"""The one reader of `module.lock.json` — the facts of a module release.

A MODULE RELEASE is a git tag, the module's images in the registry, and this lock naming their digests
(`rules/version-control.md` § *A module release*). The lock is GENERATED by `publish_module.sh` from what
the registry actually holds and never typed, and everything that needs a fact about a release asks here:
the writer (`write_module_lock.py`, in the module maintainer's scripts) builds and writes it through
`build_lock` / `write_lock`, and a deployed site (`adopt_module.sh`) reads, verifies and uses it. One module knows the
schema, so no second reader can disagree about it.

THE SHAPE, a subset of the framework's lock (no toolbox, no template part — a module is not the framework):

    { "version": "1.2.0", "published_at": "2026-10-02T09:00:00Z",
      "module": { "name": "sra", "slug": "sra" },
      "registry": "ghcr.io/owner",
      "images": { "sra.backend": "sha256:…", "sra.frontend": "sha256:…" } }

A release only: `X.Y.Z`. There is no `latest` for a module, so there is no channel to be ambiguous about.

THIS FILE IS DEPLOYED. It lives in the runtime folder, which is copied whole into every site, so it names
no development path and imports only the standard library.

    python3 scripts/runtime/module_version.py check <dir>          # the lock in <dir> is valid
    python3 scripts/runtime/module_version.py refs  <dir>          # one line per image: name pull-ref local-ref
    python3 scripts/runtime/module_version.py bake  <dir> <compose-file>   # point its images at the release
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from dataclasses import dataclass
from pathlib import Path

LOCK_FILE = "module.lock.json"

_VERSION = re.compile(r"^\d+\.\d+\.\d+$")
_DIGEST = re.compile(r"^sha256:[0-9a-f]{64}$")
_LOCK_KEYS = {"version", "published_at", "module", "registry", "images"}


class ModuleVersionError(SystemExit):
    """Every way the lock can be wrong. Exit status 1, message on stderr."""

    def __init__(self, message: str) -> None:
        self.message = message
        super().__init__(1)


@dataclass(frozen=True)
class ImageRef:
    name: str
    #: What to pull: `<registry>/<name>@<digest>` — exactly the bytes the lock names.
    pull: str
    #: What compose runs: `<registry>/<name>:<version>`, so start-up never reaches for the registry.
    local: str
    digest: str


def _text(value: object, where: str) -> str:
    if not isinstance(value, str) or not value.strip():
        raise ModuleVersionError(f"{LOCK_FILE}: {where} is empty.")
    return value


def validate_lock(lock: object) -> dict:
    """Return `lock` when it has exactly the schema the publish writes; raise otherwise."""
    if not isinstance(lock, dict):
        raise ModuleVersionError(f"{LOCK_FILE}: the document is not a JSON object.")
    unknown, missing = sorted(set(lock) - _LOCK_KEYS), sorted(_LOCK_KEYS - set(lock))
    if unknown or missing:
        raise ModuleVersionError(
            f"{LOCK_FILE}: keys must be exactly {sorted(_LOCK_KEYS)}; missing {missing}, unknown {unknown}. "
            f"The lock is generated by the module publish and never edited by hand."
        )
    version = _text(lock["version"], "`version`")
    if not _VERSION.match(version):
        raise ModuleVersionError(f"{LOCK_FILE}: `version` {version!r} is not `X.Y.Z` (a module has releases, no `latest`).")
    _text(lock["published_at"], "`published_at`")
    module = lock["module"]
    if not isinstance(module, dict) or set(module) != {"name", "slug"}:
        raise ModuleVersionError(f"{LOCK_FILE}: `module` must be exactly {{name, slug}}.")
    slug = _text(module["slug"], "`module.slug`")
    _text(module["name"], "`module.name`")
    _text(lock["registry"], "`registry`")
    images = lock["images"]
    if not isinstance(images, dict) or not images:
        raise ModuleVersionError(f"{LOCK_FILE}: `images` must map at least one image name to a digest.")
    for name, digest in images.items():
        if not isinstance(digest, str) or not _DIGEST.match(digest):
            raise ModuleVersionError(
                f"{LOCK_FILE}: images[{name!r}] is {digest!r}, not a `sha256:<64 hex>` digest. "
                f"A lock carrying anything but a registry digest was not written by the publish."
            )
        if not str(name).startswith(f"{slug}."):
            raise ModuleVersionError(f"{LOCK_FILE}: image {name!r} is not one of module {slug!r}'s (`{slug}.<component>`).")
    return lock


def parse_lock(text: str) -> dict:
    try:
        document = json.loads(text)
    except json.JSONDecodeError as exc:
        raise ModuleVersionError(f"{LOCK_FILE} is not valid JSON ({exc}). Regenerate it; do not edit it.") from exc
    return validate_lock(document)


def read_lock(directory: Path | str) -> dict:
    path = Path(directory) / LOCK_FILE
    if not path.is_file():
        raise ModuleVersionError(f"{LOCK_FILE} is missing in {directory}. It is written by `publish_module.sh`.")
    return parse_lock(path.read_text(encoding="utf-8"))


def image_refs(lock: dict) -> list[ImageRef]:
    registry, version = lock["registry"].rstrip("/"), lock["version"]
    return [
        ImageRef(name, f"{registry}/{name}@{digest}", f"{registry}/{name}:{version}", digest)
        for name, digest in sorted(lock["images"].items())
    ]


#: One `image:` line of a compose file: the value, and whatever trails it (spaces, a comment).
_IMAGE_LINE = re.compile(r"^(?P<lead>[ \t]*image:[ \t]*)(?P<value>[^\s#]+)(?P<tail>[ \t]*(?:#.*)?)$", re.MULTILINE)


def _image_name(value: str) -> str:
    """`<slug>.<component>` of an image reference, whatever its registry prefix, tag or digest.

    The registry may carry a port (`localhost:5005/sra.backend:1.0.0`), so the name is the LAST path
    segment, cut at its own `:` or `@`.
    """
    return value.strip("\"'").split("@", 1)[0].rsplit("/", 1)[-1].split(":", 1)[0]


def bake_compose(compose_text: str, lock: dict) -> str:
    """Point every one of the module's OWN images at the release: `<registry>/<name>:<version>`.

    Only an image whose name is one of the lock's is touched; a third-party image (`postgres:16-alpine`)
    never matches, and an unknown one is left alone rather than guessed at.
    """
    wanted = {ref.name: ref.local for ref in image_refs(lock)}

    def replace(match: re.Match) -> str:
        name = _image_name(match.group("value"))
        return f"{match.group('lead')}{wanted[name]}{match.group('tail')}" if name in wanted else match.group(0)

    return _IMAGE_LINE.sub(replace, compose_text)


def build_lock(*, version: str, published_at: str, name: str, slug: str, registry: str, images: dict[str, str]) -> dict:
    """Assemble a lock from published digests, refusing anything that is not one."""
    return validate_lock({
        "version": version,
        "published_at": published_at,
        "module": {"name": name, "slug": slug},
        "registry": registry.rstrip("/"),
        "images": dict(sorted(images.items())),
    })


def write_lock(lock: dict, directory: Path | str) -> Path:
    """Write a validated lock to `<directory>/module.lock.json`, stably formatted for review diffs."""
    validate_lock(lock)
    path = Path(directory) / LOCK_FILE
    path.write_text(json.dumps(lock, indent=2) + "\n", encoding="utf-8")
    return path


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="module_version.py", description="The one reader of module.lock.json.")
    parser.add_argument("command", choices=["check", "refs", "bake"])
    parser.add_argument("directory", type=Path)
    parser.add_argument("compose", nargs="?", type=Path)
    args = parser.parse_args(argv)
    try:
        lock = read_lock(args.directory)
        if args.command == "check":
            print(f"module {lock['module']['slug']} {lock['version']}: {LOCK_FILE} is valid (published {lock['published_at']})")
        elif args.command == "refs":
            for ref in image_refs(lock):
                print(f"{ref.name} {ref.pull} {ref.local}")
        else:
            if not args.compose:
                parser.error("bake needs the compose file")
            args.compose.write_text(bake_compose(args.compose.read_text(encoding="utf-8"), lock), encoding="utf-8")
            print(f"{args.compose}: images point at {lock['module']['slug']} {lock['version']}")
    except ModuleVersionError as exc:
        print(f"[module-version] {exc.message}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
