#!/usr/bin/env python3
"""Fail a deploy that is about to start images other than the ones it just built.

Two writers produce `deployment_root/.env.config` and neither can be removed:

- `build_and_deploy.py` writes it during a deploy, recording the tag it built (`BUILT_IMAGE_TAG`)
  and the tag to run (`IMAGE_TAG`) — equal, by construction.
- `scripts/runtime/config/create-merged-configuration.sh` then rewrites the whole file, preserving
  the `IMAGE_TAG` it finds. That is correct and cannot be replaced by re-deriving: the script also
  runs standalone at a deployed site, where there is no git checkout and no build, and where an
  operator's hand-edited rollback must survive the next regeneration.

Because both must exist, "what was built" and "what will run" can disagree. They did:
`redeploy.sh` scrubbed the environment with `env -i` before the build, so `IMAGE_TAG=<tag>` never
reached `image_tag()` — the build tagged the commit hash — while the merge, which runs outside that
scrub, read the same variable and wrote `<tag>`. Compose then started `<tag>`: images from an
earlier build, every container healthy, exit code 0. `status.sh` could not see it, because it
compares the configured tag with the running one and those agreed.

So the two facts are **compared**, once, after the merge. One check covers the whole class: a
dropped variable, a half-finished build, a stale merge, a merge that ran against a different
deployment_root.

**Why only after a build.** On a rollback the two values differ on purpose — the operator sets
`IMAGE_TAG` to a previous build and `BUILT_IMAGE_TAG` still records the last build. `redeploy.sh`
invokes this only when it rebuilt images, so a rollback is never refused.

Exit codes: 0 agree (or nothing to compare and it says so), 1 they disagree.
"""
import os
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
_PROJECT_ROOT = os.path.dirname(os.path.dirname(_HERE))


def read_tags(env_config_path):
    """Return (IMAGE_TAG, BUILT_IMAGE_TAG) from a merged .env.config, '' for either if absent.

    Last assignment wins, matching how `set -a; source` resolves the file — the same file the
    runtime scripts read, so this reads what compose will actually see rather than the first line
    that happens to match.
    """
    image_tag = ""
    built_tag = ""
    if not os.path.isfile(env_config_path):
        return image_tag, built_tag
    with open(env_config_path, encoding="utf-8") as handle:
        for line in handle:
            line = line.strip()
            if line.startswith("BUILT_IMAGE_TAG="):
                built_tag = line.split("=", 1)[1].strip()
            elif line.startswith("IMAGE_TAG="):
                image_tag = line.split("=", 1)[1].strip()
    return image_tag, built_tag


def verify(env_config_path):
    """(ok, message). Not a print-and-exit, so the contract test can assert the outcomes."""
    if not os.path.isfile(env_config_path):
        return False, (
            "ERROR: {} does not exist after the deploy.\n"
            "  Nothing wrote the merged configuration, so compose has no image tags to resolve."
        ).format(env_config_path)

    image_tag, built_tag = read_tags(env_config_path)

    if not image_tag:
        return False, (
            "ERROR: no IMAGE_TAG in {}.\n"
            "  Every compose image reference would resolve to `name:`, which docker rejects."
        ).format(env_config_path)

    if not built_tag:
        # A deployment_root written by an older build, regenerated by a newer script. Say so
        # plainly: reporting "verified" here would be a check that cannot fail claiming success.
        return True, (
            "NOTE: no BUILT_IMAGE_TAG in {}, so the built tag could not be compared with the tag "
            "that will run (IMAGE_TAG={}). Re-run ./redeploy.sh to record it."
        ).format(env_config_path, image_tag)

    if image_tag != built_tag:
        return False, (
            "ERROR: this deploy built one tag and is about to start another.\n"
            "    built   (BUILT_IMAGE_TAG): {built}\n"
            "    will run    (IMAGE_TAG): {run}\n"
            "  {path}\n"
            "\n"
            "  The stack would run images from a different build than the one that just finished,\n"
            "  with every container healthy and nothing to show it. Likely causes:\n"
            "    - IMAGE_TAG is pinned in project.env.config to a value the build did not use;\n"
            "    - the merged configuration was regenerated with a different IMAGE_TAG in the\n"
            "      environment than the build received;\n"
            "    - a previous build left {run} behind and this one did not overwrite it.\n"
            "\n"
            "  State the tag once, for both: ./redeploy.sh --image-tag {built}"
        ).format(built=built_tag, run=image_tag, path=env_config_path)

    return True, "Build identity verified: built and running tag are both {}".format(built_tag)


def main(argv):
    env_config_path = argv[1] if len(argv) > 1 else os.path.join(
        _PROJECT_ROOT, "deployment_root", ".env.config"
    )
    ok, message = verify(env_config_path)
    print(message)
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main(sys.argv))
