import { existsSync, readFileSync } from 'node:fs'
import path from 'node:path'
import { test, expect } from '@playwright/test'
import { parseEntityGraph } from '../lib/entity-graph'

// Stack-free unit test for the FK dependency-tree helper used by FK-aware CRUD specs.
// Runs in every test phase (no auth / no running stack).

const SQL = `
CREATE TABLE IF NOT EXISTS company ( id serial PRIMARY KEY, name text );
CREATE TABLE IF NOT EXISTS asset (
  id serial PRIMARY KEY,
  company_id integer NOT NULL,
  FOREIGN KEY (company_id) REFERENCES company (id)
);
CREATE TABLE IF NOT EXISTS map (
  id serial PRIMARY KEY,
  asset_id integer REFERENCES asset(id),
  parent_map_id integer REFERENCES map(id)  -- self-ref, ignored for ordering
);
`

test.describe('entity-graph — FK dependency tree', () => {
  test('records parents and orders leaves before dependents', () => {
    const g = parseEntityGraph(SQL)
    expect([...g.entities].sort()).toEqual(['asset', 'company', 'map'])
    expect(g.parents.asset).toEqual(['company'])
    expect(g.parents.map).toEqual(['asset']) // self-ref to map is dropped
    expect(g.cycles).toEqual([])
    // company (leaf) before asset before map
    expect(g.createOrder.indexOf('company')).toBeLessThan(g.createOrder.indexOf('asset'))
    expect(g.createOrder.indexOf('asset')).toBeLessThan(g.createOrder.indexOf('map'))
  })
})

// The hand-written fixture above is the shape the helper was WRITTEN for, and passing it proved
// nothing about the shape it is actually given. `database/SPECS/schema.sql` is generated by
// pg_dump: table names are schema-qualified and foreign keys arrive as separate ALTER statements,
// neither of which the original parser could read — so a module with real FKs produced an empty
// graph, silently, and the mandatory FK ordering ordered nothing.
const GENERATED = `
CREATE TABLE public.companies (
    id integer NOT NULL,
    name character varying(255) NOT NULL
);

CREATE TABLE public.assets (
    id integer NOT NULL,
    company_fk integer NOT NULL
);

ALTER TABLE ONLY public.assets
    ADD CONSTRAINT assets_company_fk_fkey FOREIGN KEY (company_fk) REFERENCES public.companies(id) ON DELETE CASCADE;
`

test.describe('entity-graph — the generated schema shape', () => {
  test('reads schema-qualified names and post-table FK constraints', () => {
    const g = parseEntityGraph(GENERATED)
    expect([...g.entities].sort()).toEqual(['assets', 'companies'])
    expect(g.parents.assets).toEqual(['companies'])
    expect(g.parents.companies).toEqual([])
    expect(g.cycles).toEqual([])
    // the parent is created first, so a child's FK can be valorized with a real id
    expect(g.createOrder.indexOf('companies')).toBeLessThan(g.createOrder.indexOf('assets'))
  })

  test('finds the real FKs in a real generated schema, not only in a fixture', () => {
    // host_app's schema is the one in this repository that HAS foreign keys. Skipped rather than
    // failed where it is absent: a remote module project does not receive host_app's sources.
    // `__dirname` is undefined here — the harness runs as ESM — so the anchor is this spec's own
    // absolute path, which Playwright reports.
    const schema = path.resolve(
      path.dirname(test.info().file), '../../../../../host_app/database/SPECS/schema.sql',
    )
    test.skip(
      !existsSync(schema),
      'host_app/database/SPECS/schema.sql is absent — this is a remote module project, which ' +
      'carries host_app as pre-built images',
    )
    const g = parseEntityGraph(readFileSync(schema, 'utf8'))
    expect(g.entities.length).toBeGreaterThan(5)
    const withParents = Object.entries(g.parents).filter(([, ps]) => ps.length > 0)
    expect(
      withParents.length,
      'no FK edges found in a schema that demonstrably has them — the parser is not reading the ' +
      'generated form',
    ).toBeGreaterThan(0)
    // every edge points at a table the same schema declares
    for (const [child, ps] of withParents) {
      for (const parent of ps) {
        expect(g.entities, `${child} -> ${parent}`).toContain(parent)
      }
    }
  })
})
