"""sub_item_notes: the association chain's third level

Revision ID: 041b319b9b9d
Revises: 2611b5d150a7
Create Date: 2026-09-22 18:25:20.148894
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '041b319b9b9d'
down_revision: Union[str, None] = '2611b5d150a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sub_item_notes_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('sub_item_fk', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('name', sa.String(length=255), autoincrement=False, nullable=True),
    sa.Column('description', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id', 'issued_at')
    )
    op.enable_rls('sub_item_notes_version')
    op.create_tenant_policies('sub_item_notes_version')
    op.create_index(op.f('ix_sub_item_notes_version_end_transaction_id'), 'sub_item_notes_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_sub_item_notes_version_id'), 'sub_item_notes_version', ['id'], unique=False)
    op.create_index(op.f('ix_sub_item_notes_version_operation_type'), 'sub_item_notes_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_sub_item_notes_version_sub_item_fk'), 'sub_item_notes_version', ['sub_item_fk'], unique=False)
    op.create_index(op.f('ix_sub_item_notes_version_tenant_id'), 'sub_item_notes_version', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_sub_item_notes_version_transaction_id'), 'sub_item_notes_version', ['transaction_id'], unique=False)
    op.create_table('sub_item_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('sub_item_fk', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['sub_item_fk'], ['sub_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.enable_rls('sub_item_notes')
    op.create_tenant_policies('sub_item_notes')
    op.create_index('idx_sub_item_notes_name_trgm', 'sub_item_notes', ['name'], unique=False, postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    # NO `idx_sub_item_notes_sub_item_fk_trgm`: autogenerate emitted one, and it cannot run —
    # `gin_trgm_ops` is an operator class for TEXT, so `CREATE INDEX ... USING gin (sub_item_fk
    # gin_trgm_ops)` on an integer column is an error, not a slow index. `sub_item_fk` is declared
    # `__filterable__` and is exact-matched, so the plain index below is the one its filter uses.
    op.create_index('idx_sub_item_notes_name', 'sub_item_notes', ['name'], unique=False)
    op.create_index('idx_sub_item_notes_sub_item_fk', 'sub_item_notes', ['sub_item_fk'], unique=False)
    op.create_index('idx_sub_item_notes_tenant_id', 'sub_item_notes', ['tenant_id', 'id'], unique=False)
    op.create_index(op.f('ix_sub_item_notes_id'), 'sub_item_notes', ['id'], unique=False)
    op.create_index(op.f('ix_sub_item_notes_sub_item_fk'), 'sub_item_notes', ['sub_item_fk'], unique=False)
    op.create_index(op.f('ix_sub_item_notes_tenant_id'), 'sub_item_notes', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_sub_items_item_fk'), 'sub_items', ['item_fk'], unique=False)
    op.create_index(op.f('ix_sub_items_version_item_fk'), 'sub_items_version', ['item_fk'], unique=False)
    op.create_hypertable('sub_item_notes_version', time_column='issued_at', chunk_interval='7 days')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sub_items_version_item_fk'), table_name='sub_items_version')
    op.drop_index(op.f('ix_sub_items_item_fk'), table_name='sub_items')
    op.drop_index(op.f('ix_sub_item_notes_tenant_id'), table_name='sub_item_notes')
    op.drop_index(op.f('ix_sub_item_notes_sub_item_fk'), table_name='sub_item_notes')
    op.drop_index(op.f('ix_sub_item_notes_id'), table_name='sub_item_notes')
    op.drop_index('idx_sub_item_notes_tenant_id', table_name='sub_item_notes')
    op.drop_index('idx_sub_item_notes_sub_item_fk', table_name='sub_item_notes')
    op.drop_index('idx_sub_item_notes_name', table_name='sub_item_notes')
    op.drop_table('sub_item_notes')
    op.drop_index(op.f('ix_sub_item_notes_version_transaction_id'), table_name='sub_item_notes_version')
    op.drop_index(op.f('ix_sub_item_notes_version_tenant_id'), table_name='sub_item_notes_version')
    op.drop_index(op.f('ix_sub_item_notes_version_sub_item_fk'), table_name='sub_item_notes_version')
    op.drop_index(op.f('ix_sub_item_notes_version_operation_type'), table_name='sub_item_notes_version')
    op.drop_index(op.f('ix_sub_item_notes_version_id'), table_name='sub_item_notes_version')
    op.drop_index(op.f('ix_sub_item_notes_version_end_transaction_id'), table_name='sub_item_notes_version')
    op.drop_table('sub_item_notes_version')
    # ### end Alembic commands ###
