FROM node:20-alpine as build

WORKDIR /app

COPY package.json ./
RUN npm install --legacy-peer-deps

COPY . .

ARG VITE_APP_TITLE
ARG VITE_TEMPLATE_API_URL

ENV VITE_APP_TITLE=$VITE_APP_TITLE
ENV VITE_TEMPLATE_API_URL=$VITE_TEMPLATE_API_URL

RUN npm run build

FROM nginx:alpine

COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
