-- NOTE: SQLAlchemy-Continuum audit trail tables (`transaction` and `template_items_version`)
-- are auto-generated by the ORM at startup via Base.metadata.create_all() and are NOT
-- defined here. For production environments using Alembic, those tables are managed by
-- Alembic migrations instead.

CREATE TABLE IF NOT EXISTS template_items (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT
);

CREATE INDEX IF NOT EXISTS idx_template_items_name ON template_items(name);
